import json
import os
import unittest

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
FRANCHISES_PATH = os.path.join(REPO_ROOT, "data", "2026-27", "franchises.json")
ROSTERS_PATH = os.path.join(REPO_ROOT, "data", "2026-27", "prekeeper_rosters.json")

CANONICAL_ORDER = [
    "Hai | GTA San Antonio",
    "CrazyCat Damageee",
    "MeloBB",
    "Long con",
    "HCMC Kindergarten",
    "Dũng | Trader by Trade",
    "Maxfixe",
    "DHA | Đì troi pít tông",
    "M. Jordat | The Silver Seekers",
    "DonTrick DevilTeam",
    "Thịnh | Seattle SuperSonics",
    "sup fam | Bruised for Boozer",
    "Quan | Okay See Thunder",
    "TuLy | No Country for Old Men",
    "Bz | Putin the tank driver",
    "TT | Kratos Dynasty",
]

EXPECTED_ROSTER_COUNTS = [15, 15, 14, 15, 13, 14, 13, 15, 13, 15, 15, 15, 15, 15, 15, 15]
EXPECTED_TOTAL = 232

# Ownership-regression anchors only -- NBA-team/cap metadata is intentionally
# not asserted here (that comes from the live Yahoo source, not this snapshot).
ANCHOR_OWNERSHIP = {
    "Victor Wembanyama": "franchise-01",
    "Giannis Antetokounmpo": "franchise-03",
    "Karl-Anthony Towns": "franchise-04",
    "Luka Dončić": "franchise-09",
    "Cooper Flagg": "franchise-12",
    "Shai Gilgeous-Alexander": "franchise-13",
    "Nikola Jokić": "franchise-11",
    "Donovan Mitchell": "franchise-16",
}


class TestFranchiseBaseline(unittest.TestCase):
    """These assertions depend only on data/2026-27/franchises.json, which
    is derived directly from the canonical team order given in this
    project's bootstrap spec -- no forensic source file required."""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(FRANCHISES_PATH):
            raise unittest.SkipTest(f"{FRANCHISES_PATH} not found")
        with open(FRANCHISES_PATH, encoding="utf-8") as f:
            cls.data = json.load(f)

    def test_exactly_16_franchises(self):
        self.assertEqual(len(self.data["franchises"]), 16)

    def test_canonical_order_and_display_names(self):
        names = [f["displayName"] for f in self.data["franchises"]]
        self.assertEqual(names, CANONICAL_ORDER)

    def test_stable_franchise_ids(self):
        ids = [f["franchiseId"] for f in self.data["franchises"]]
        expected = [f"franchise-{i:02d}" for i in range(1, 17)]
        self.assertEqual(ids, expected)


class TestPreKeeperRosterBaseline(unittest.TestCase):
    """These assertions require data/2026-27/prekeeper_rosters.json, which
    can only be generated by scripts/import_forensic_rosters.py against the
    real forensic snapshot markdown. That source file was not available at
    bootstrap time (see docs/OPEN_RULE_QUESTIONS.md) -- this suite skips
    cleanly rather than failing CI until the file is supplied and imported."""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(ROSTERS_PATH):
            raise unittest.SkipTest(
                f"{ROSTERS_PATH} not found -- forensic source file not yet "
                f"imported, see docs/OPEN_RULE_QUESTIONS.md"
            )
        with open(ROSTERS_PATH, encoding="utf-8") as f:
            cls.data = json.load(f)
        cls.assignments = cls.data["assignments"]

    def test_total_assignments(self):
        self.assertEqual(len(self.assignments), EXPECTED_TOTAL)

    def test_per_franchise_counts(self):
        counts = {}
        for a in self.assignments:
            counts[a["franchiseId"]] = counts.get(a["franchiseId"], 0) + 1
        ordered = [counts.get(f"franchise-{i:02d}", 0) for i in range(1, 17)]
        self.assertEqual(ordered, EXPECTED_ROSTER_COUNTS)

    def test_no_duplicate_ownership(self):
        names = [a["playerName"] for a in self.assignments]
        self.assertEqual(len(names), len(set(names)))

    def test_anchor_ownership_facts(self):
        by_name = {a["playerName"]: a["franchiseId"] for a in self.assignments}
        for player, expected_franchise in ANCHOR_OWNERSHIP.items():
            self.assertEqual(
                by_name.get(player), expected_franchise,
                msg=f"expected {player} on {expected_franchise}",
            )


if __name__ == "__main__":
    unittest.main()
